apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cache
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: default
  sources:
    - repoURL: oci://registry-1.docker.io/cloudpirates/redis
      targetRevision: 0.25.1
      path: .
      helm:
        releaseName: redis-cache
        valueFiles:
          - $values/deploy/infrastructure/base/workloads/redis-cache/values.yaml
          - $values/deploy/environments/local/workloads/redis-cache/values.yaml
    - repoURL: git@github.com:The-Supremacy/ProperTea.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
