# This is a generated file. Not intended for manual editing.
services:
  landlord-bff:
    build:
      context: "/home/oxface/repos/The-Supremacy/ProperTea"
      dockerfile: "src/services/Gateway/ProperTea.Landlord.Bff/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/ProperTea.Landlord.Bff.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "propertea.landlord.bff:dev"
    ports: []
    volumes:
    - "/home/oxface/repos/The-Supremacy/ProperTea/src/services/Gateway/ProperTea.Landlord.Bff:/app:rw"
    - "/home/oxface/repos/The-Supremacy/ProperTea:/src:rw"
    - "/home/oxface/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
