# This is a generated file. Not intended for manual editing.
services:
  landlord-bff:
    build:
      context: "/home/oxface/repos/The-Supremacy/ProperTea"
      dockerfile: "src/services/Gateway/ProperTea.Landlord.Bff/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57432"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "propertea.landlord.bff:dev"
    ports:
    - "127.0.0.1:57032:57000"
    - "127.0.0.1:57232:57200"
    - "127.0.0.1:57432:57432"
    volumes:
    - "/home/oxface/repos/The-Supremacy/ProperTea/src/services/Gateway/ProperTea.Landlord.Bff:/app:rw"
    - "/home/oxface/repos/The-Supremacy/ProperTea:/src:rw"
    - "/home/oxface/.nuget/packages:/home/app/.nuget/packages"
    - "/home/oxface/.local/share/JetBrains/RiderRemoteDebugger/2025.3.0.3/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/snap/rider/674/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/oxface/.cache/JetBrains/Rider2025.3/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_12_02_19_04_31:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  organization-api:
    build:
      context: "/home/oxface/repos/The-Supremacy/ProperTea"
      dockerfile: "src/services/Organization/ProperTea.Organization/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57433"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "propertea.organization:dev"
    ports:
    - "127.0.0.1:57033:57000"
    - "127.0.0.1:57233:57200"
    - "127.0.0.1:57433:57433"
    volumes:
    - "/home/oxface/repos/The-Supremacy/ProperTea/src/services/Organization/ProperTea.Organization:/app:rw"
    - "/home/oxface/repos/The-Supremacy/ProperTea:/src:rw"
    - "/home/oxface/.nuget/packages:/home/app/.nuget/packages"
    - "/home/oxface/.local/share/JetBrains/RiderRemoteDebugger/2025.3.0.3/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/snap/rider/674/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/oxface/.cache/JetBrains/Rider2025.3/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_12_02_19_04_31:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
