# This is a generated file. Not intended for manual editing.
services:
  organization-api:
    build:
      context: "/home/oxface/repos/The-Supremacy/ProperTea"
      dockerfile: "src/services/Organization/ProperTea.Organization/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/ProperTea.Organization.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "propertea.organization:dev"
    ports: []
    volumes:
    - "/home/oxface/repos/The-Supremacy/ProperTea/src/services/Organization/ProperTea.Organization:/app:rw"
    - "/home/oxface/repos/The-Supremacy/ProperTea:/src:rw"
    - "/home/oxface/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
