replicaCount: 1

keycloak:
  adminUser: admin
  adminPassword: "Password1!"
  hostname: "keycloak.local"

database:
  type: postgres
  host: keycloak-db-rw
  port: 5432
  name: keycloak
  existingSecret: keycloak-db-app
  secretKeys:
    # Keys present in the CNPG-generated keycloak-db-app secret.
    passwordKey: password
    usernameKey: username
