apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alloy.yaml
  - grafana.yaml
  - kube-state-metrics.yaml
  - loki.yaml
  - metrics-server.yaml
  - tempo.yaml
  - victoria-metrics.yaml
