apiVersion: ENC[AES256_GCM,data:amI=,iv:nvh6ulZL5Vq7+v7QRG1hI1WWctWiHd2V7TAAcFjgyJU=,tag:ejJEZTrojvvxWJaM5WcElg==,type:str]
kind: ENC[AES256_GCM,data:7Ec4oO9I,iv:F7Vbp3lqf9lmm0GrdKscYbY/vQRuh3VeW8lCH73UZSU=,tag:Otuetk6bbXs57MFKFszKXA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XqPlAL88xv11bYgE7mkSiQTWHVKFZtlFP7ww03ryJ0E42T/FBQ==,iv:dh9T4wUfwYL4iigxfsUHTzZdUu0cHGt4wg+wVR07svo=,tag:y7BKfyFWIKgLdfEbS6vmHQ==,type:str]
    namespace: ENC[AES256_GCM,data:Bj2HxebA,iv:/TkBLmajQ9N22xAMXPKHsq7EaCEsFWeZOqaD9fUoCZs=,tag:R2n/ds2ZFKTMCBOt+L1/iA==,type:str]
    labels:
        argocd.argoproj.io/secret-type: ENC[AES256_GCM,data:34qDmZFcvUf39A==,iv:vnjNIrNp1+5xnMi1C5No+qF/5IiwiPy4oH0LT/hG8tY=,tag:J65JOjTazaePI+DXG/G/9Q==,type:str]
stringData:
    url: ENC[AES256_GCM,data:UOr4j7YOhuIJEAQuQrq0TKLq5HfGUMs/IkLAougF2CNzyCFlkTfKWFk=,iv:i/UuYKd/ntaadOUBkwphQxufBXjmrrj8RzaJfcisEfg=,tag:bFCB+7LWd+vKwDCCysL5Pg==,type:str]
    type: ENC[AES256_GCM,data:VLq8Cw==,iv:Wy+0QBfTrO+Zdne4EQ60wTEyjM1Yt5aTsgqWYnMuWdg=,tag:IqGsEsMRX5GGL9iE4TOLHQ==,type:str]
    name: ENC[AES256_GCM,data:8fbGp/+m8oJ9oP3A3VzjUInGj6k=,iv:3FRIsRnUFYp1CIhwX6gCBOkfVYMkFbh18Jb87TxKhLI=,tag:ShmTHuS/vVDeyZNwwzYIyg==,type:str]
    enableOCI: ENC[AES256_GCM,data:h/psFw==,iv:2jh1AotwGYfhlUpwZ8Akq+nOk5XLCCbTQkx5EnV4Kyk=,tag:31stvfBlJxX53qieZ9BtNg==,type:str]
    username: ENC[AES256_GCM,data:zHLnP7Yx,iv:IExMSn7YR27dY3d8J5adqLgaXL6VLwLUttYaKpKhIwc=,tag:ffYu8MIhIsUH9pog1gnamg==,type:str]
    password: ENC[AES256_GCM,data:wlicJ6NmwJyevGD8XyhRNh/9AZXXRGxsfQZD79ZEv673GBiCUVzAhw==,iv:pd+VZPRpYFvjanJZ5RkoK6AlRQzDE4i6ERCdV/asJLE=,tag:OW2eh+TK2Q+EYWbLnPVFqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18wk5cvj6z2lu239q9z748xmqmn660dqdermety58a7e2zrte8yqq3rw7k6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERktiSFMzVmZlY2xJL1pF
            cUJHYXBvS09xVVZteDlNUnNCckU2ZDdHWm1JCkVpSjZ1UldmTzh2djZCRVlVcG50
            OXNlSlQ2cVByUTh3UEErNEJEOXkrUDAKLS0tIGVWYTNOQXlJY2lTZk92VUxZSjVQ
            Q0luTGVhVWpVZlp4ekV3ZWRxWk0xcjgK52AF2LqTuN09/iD8xXwtxiUW7KuH1kL8
            KOEhq7YF+bx2VAO610NrE7f0nJmbyAGS8FRHvdgJb5MxMJxvlUdQDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T23:39:33Z"
    mac: ENC[AES256_GCM,data:1jL4vuV97Hq+blCwJFIDZcSr8vfcB16Ovhho3fo22HAtqKD+JKQcCf1LhNvZ5Kuz4oaL8d7aV9pg5Kp4THn8uiwR/i5PQJTi/7OyIu3GlzwsshwLKKBoFrXUQ9hIvY3l4HODRnwuY6TYU66elN8OYNk9RlnemuIa3eeRg4rlhzA=,iv:CXnGqLTV86Sk/Ch2J4OC5IGCntljAzAb5rGp0OUZTPQ=,tag:2ypNhjsHUnqnipR3mELnzQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
