apiVersion: ENC[AES256_GCM,data:2hg=,iv:kHpXNUGFPZNb5ZEUj4dT1d0QYX4/Sa9xCyJM4l/Fsq4=,tag:wqHRmJEELA/JsV65jAuqLA==,type:str]
kind: ENC[AES256_GCM,data:4qiR9pBb,iv:oml+fBqA3+Bg679RPcoXHvJA1+87A5O9BYdgOo12tzw=,tag:2tIyX3oGiAoUL2JSdLwMiQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ta7+k6zVFsp5wds44SLvLpywHAl6,iv:M8MwShQSmscay8NW6jHyeypEdSbIxyLFcvFqRFGOhaE=,tag:7IJ3DDrmyTF6+g9+cpHZ6g==,type:str]
    namespace: ENC[AES256_GCM,data:mATLwrRQ,iv:bLVO/AEFrgc5WpcYJ6D9wUtkJ7fVaY+jxZqgMSEivN8=,tag:p4xHQIn+jhTqO26B9XOh0w==,type:str]
    labels:
        argocd.argoproj.io/secret-type: ENC[AES256_GCM,data:+/Npmyav+xK3Kg==,iv:b6LvPQPNgOY+ZA8VxxtUKjJls3DFdB7/OBuhC1rnZ6I=,tag:USANQ3/3jw/jt1BL+v5Esw==,type:str]
stringData:
    url: ENC[AES256_GCM,data:JK+QqkNH2Rn3F+y68gAdD69nVtSmKYQXmPN1It8SxwjmPNCiaEff,iv:IvxAwjZ2FepshqdEKjLEli1GABBZvSLjZwLBh1gWQWM=,tag:ld//soL+TUjR/0hPnVThzQ==,type:str]
    type: ENC[AES256_GCM,data:HhbrxA==,iv:2ZK93McTuofmrMZopP1j8l5gzrZilwVHKCFCtwv5gno=,tag:5ebOR6wVC1ph5Wi0CTStHQ==,type:str]
    name: ENC[AES256_GCM,data:zuI/rWZ9fr6iUsqI,iv:YsC9OxQX+ZCa96R6k2eITSvYzuwfNzKBUfekD72FUYo=,tag:HYq+smejQ6GCxiYCHGPRRg==,type:str]
    enableOCI: ENC[AES256_GCM,data:4A21vw==,iv:FvLrH5W3eKsYnBH4Z+Cb+qFoRgW4afQYrFlbdT3cf2M=,tag:obSa+r6FnKxsHJ6RCMyPag==,type:str]
    username: ENC[AES256_GCM,data:rhX0Qz1f,iv:W3oyZSJ1fBxjqkLiLBt/d6pUQH4MlWEqyxcNtACXk10=,tag:e651U4FJtL0DWEaMi/WWJw==,type:str]
    password: ENC[AES256_GCM,data:yXWvH+f74ZS9sKEJ4VRiBFyZOJeOX/0+f6ngw5z1AC026dAr,iv:Ww0GfncFMg/EY/dIzrZKwf9qbfIry5rGO3hJCeNLewU=,tag:/VGi5E3rOJ2UUG5bJIJdCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18wk5cvj6z2lu239q9z748xmqmn660dqdermety58a7e2zrte8yqq3rw7k6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYa29pS2twTk1MU2Q0clZ1
            UElBbGtNbTk3STVIWHVieFU0TVQya083V1RnClA1ckcrU0tKaTBnOXc3ajVLcWJC
            MVFTOC9IbmNCSmhtcHMwV2ordjZYY2MKLS0tIE9XOTlDNys1ekkwZXZUUjhjemtH
            bzFFUVFUNXpQZ1ZiVnNXVTJTMk5KMWcK+/0zRyNcnnby1RbQHf+6rfQV9WK55yUA
            MaMoa/4sxcWahPbQI5Sx6iPMLln552iJ4YReHoKL1S2QlxxUzIdYFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T23:39:33Z"
    mac: ENC[AES256_GCM,data:7G+zWfLjto165ekgH1lSfO/K6hkrfMZuyFQGBFAkG047Swl4mZzVvKVmxfQS0dlptZW48fh0coC0WrwZFPDNzPnsfngcNKd6Rne4Bz3TgX/F2MNI1+BM/664fvG2b53rHbeCujj1QB/nBmmrQ94XPxzAz5B4ArOq3514/eDsc+k=,iv:YbselTTiQXfFi0v3rPJAudmiLbYsQJqAKsDwPI2VZII=,tag:FuWdITLYStGScfi5bxxS+w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
