apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd.yaml
  - argocd-config.yaml
  - cert-manager.yaml
  - cert-manager-config.yaml
  - cloudnativepg.yaml
  - gateway-config.yaml
  - longhorn.yaml
  - longhorn-config.yaml
  - zitadel-config.yaml
  - zitadel.yaml
