apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd.yaml
  - argocd-config.yaml
  - cert-manager.yaml
  - cert-manager-config.yaml
  - cloudnativepg.yaml
  - gateway-config.yaml
  - longhorn.yaml
  - longhorn-config.yaml
  - infisical.yaml
  - secrets-operator.yaml
  - keycloak-config.yaml
  - keycloak.yaml
  - redis.yaml
  - rabbitmq.yaml
  - mailpit.yaml
  - pgadmin.yaml
  - redisinsight.yaml
  - metrics-server.yaml
  - kube-state-metrics.yaml
  - victoria-metrics.yaml
  - loki.yaml
  - tempo.yaml
  - alloy.yaml
  - grafana.yaml
