apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: local-pool
spec:
  blocks:
    - start: 192.168.50.200
      stop: 192.168.50.210

---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: local-l2
spec:
  loadBalancerIPs: true
  interfaces:
    - ens3

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: propertea-gateway
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: propertea-ca-issuer
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      hostname: "*.local"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: propertea-gateway-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All