apiVersion: ENC[AES256_GCM,data:SC8=,iv:inX33RIema/pAiUcByPnBURaaNAP7m4SBKO1wBf82oQ=,tag:yqQ07BC+WF6+O4yzg2N5fw==,type:str]
kind: ENC[AES256_GCM,data:sNgUP+k3,iv:aHWyFZL9Jx3sVhFLfAa5LqANuIYD4HJztS02DTZZ/y4=,tag:MB2+QtVx7a5p6ZsFLbPQYg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FuzUJ7EPVlkhhvN//WMpQ1Y=,iv:lK9g/Gimk/HOkLFjQD+xNoaYyzAFV+7cU3enARioY7E=,tag:g1aHBUGMbI+U3L9jctRRZQ==,type:str]
    namespace: ENC[AES256_GCM,data:9fZvYMSdN3vb,iv:cnp7NO5fw3hRWM+AAvxI14wKCFfxJQc69Qol+yzYkZY=,tag:v9wfvnb6YqrZG6vz3Vqu+g==,type:str]
type: ENC[AES256_GCM,data:4FWO1mKp,iv:YoOobtwL3O+loXGV7idCEw8HZYDuJDZDbXomI5O2jbQ=,tag:oO/eGs1Frkd8JmDqZW8qDQ==,type:str]
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:XPXNBgBvwPNykWRK7ENRxLjmju2099hFXSe1H2VjWnk=,iv:kTt/2sa9gIi+xOW279MntWUzaJqpG2whmTJ2qejfHV8=,tag:j+zZ/fTP+3ENrGx5SlzREQ==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:lk8C03b+GUgYFJ1kHp6HzGqSHZf2fIlwPW+jnYKX2cW+Qu1G+dHI/4aq3fU=,iv:fqZkQThdV0yeVoJskisu6kK9BJJuiOZ88gcxMx2c08A=,tag:OB6csh4TcwyZ9igCx03ZkA==,type:str]
    SITE_URL: ENC[AES256_GCM,data:UAlSukgJ0UOrCc0Eps6X3iE2fYTffIw=,iv:Ce7PvQrB3pFbxPnd5/EuN43U+PFUkJDN+0fCUo/yF7I=,tag:KfDxXw79O51ZA9ldMpH0MA==,type:str]
    DB_CONNECTION_URI: ENC[AES256_GCM,data:Y7KfVM8WGTxSwj1K0K0/+fxSPg1pCsImLMpGg2wF8sd+IQBrtA5ygcveDbNjLNiXbpvXgLvvvvLkny3i,iv:blOVsxNnNw88TWwYvciVYAVeo50DKyuUVqMiovjPfA8=,tag:mlw8F/3mMd7dv+6FrWPS1A==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:XYSRFeylw/+YWFk7Bd9ZJR0LU36XrfZ3i4qsSo0CIe57cSpC,iv:WLOOFfki/+0hIRNdRwMRKD8eOE+M7IpgmFN/Ve7W/eY=,tag:J2G1kEzokp6cL5Sr/HqVpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18wk5cvj6z2lu239q9z748xmqmn660dqdermety58a7e2zrte8yqq3rw7k6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRVg1QzF3YmJpS2YyOHd3
            MGl1WkV4eGtYbVZHeW1vNmpVaHRNWGZjaEM0CmpwUWh5ZkVQZWw0VVhqZDhVakMv
            ZzUzSlE4QUZFT09laDlzeExHTWw2MHcKLS0tIDJ4Y0RzdGk0S3lnam1MRFNzWk9P
            d3FLeEw2TlVMV0JIUElvSFFOc3FnYlUK/rNVTsxrNqeyFYy7V4VCrUZYm9IkVUJW
            ljWD4bpzb20EWPbybs0OsZCR0K4IPhhP30LZF83k+dvn31pndg2h6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T22:58:16Z"
    mac: ENC[AES256_GCM,data:m1kn7dY0E9gPozMIh7WgHrfOSuZo6Dg4zEnQYCWgbEAtmgtVuMmsJPB/61xYyvS1/NZrFOS7/GyGt3LDEqWiIRPu9yhNOen+plvK8b8C8+Um+2nyM8VaKZSdHjCOq2lp1hg+rgJEo1u7MxwFdPO5kEa/o+g11+VjjtNFA5Hgp68=,iv:KaO3XoRg7kNcV0vglA+gUi42Dnd1nGMtsb1GUI/fZUk=,tag:RmoUhPWP0/ia+gpf2R72Hw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
