apiVersion: ENC[AES256_GCM,data:Gsw=,iv:v73ZqH3OPsy+3DHH3gaqA0ZC9MSWerW9KWO18m4Ucz8=,tag:OAcWxubCeIwDIu/sfUAuDw==,type:str]
kind: ENC[AES256_GCM,data:BMPha51I,iv:DBEVc4cZc/xkaKSY9RzBBqp/ZwLYMNhyRgJaFfBw2jQ=,tag:WvrwVp8rwQ0nvEfVwqdevA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Vz0jY21Ih+slFq8d4uIafSzQoGMkm6eBuvo=,iv:BXehyrilduF4eowhDCIW/7Tg/FagX29U8zh46E7+iJ4=,tag:BsTBcJeqgi68P/Czmp3x3w==,type:str]
    namespace: ENC[AES256_GCM,data:8jYlq+A43w==,iv:S3YCdYF3e+cxYYBgz8zmI4PqZMVgQWrFsmigQy9NVKY=,tag:BN2tLB05vztF36wQOmTlYA==,type:str]
type: ENC[AES256_GCM,data:/QJvDvJb,iv:53QLeP92kfz76WdkahCrQQU2ahqar78Z5VmXxLViKzQ=,tag:T4bYLlIsTeyiDLG+KzqKVw==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:ocfZcsWiS6277hNcJEz6HHJFxUtPfQELpL4s9R8G/EzjedMp,iv:O8dSLHkourGa1tHq6sH6/I2LrIMxZuH5Xst88Wc823w=,tag:fWpvye0E4imXpB89t+ub0Q==,type:str]
    clientSecret: ENC[AES256_GCM,data:2ZNhUTiT68CDV8lIJy3z1diP1sBs8Y3onivD0sQnudlwin708GwPBIYg+SpLsg3zqBM1gOMMOu5tD3cgE8uD6Q==,iv:ifl13q2XFRbRg8ZQg1SUeFerrfetXdLjsq8WZ+TwPS0=,tag:oojxAbQ9FlXRSzul0sV8Uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18wk5cvj6z2lu239q9z748xmqmn660dqdermety58a7e2zrte8yqq3rw7k6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Rnl0cU1GM3kva2dxeXh0
            andBZVZGc2RiOHY4cFRpNzRHMkIzaFpEajE4ClArSnNURlZLM2ttZlE4YWcyVkxX
            cWcvVHJ4aG00R2N4VkZWVjFOcE5DRDQKLS0tIE4wVEp3ODNnVFN0MThVblNNa3NB
            ZjJUQnVoRCsxdSs5TnpUWXpOczIyWW8KTtAuzzwuIp7hy21xMKWNQ8Vax2lgYJ7e
            FS0vWkNoQ01T/1oo3tqSAC8ONejvb7zivCWT8ndmMU8bBO1lJbmixQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T07:05:09Z"
    mac: ENC[AES256_GCM,data:4n9UJK+oWURoXgXlkNcrlSvTtDEUBSCAHMsIbB8N5/QYXUGJCvHUplFZ3CVDeyCzAE/qwN/RpBhAK4WQ4at+HLgLFgpLB7SSuWrZKlw17TKZ4wyAEOL159so1DGxzIRi1nEfuZ2yx43YLM3AjtcWI6QvESJoCopoDLeQnXYnfxA=,iv:Vmh1hHhTbYMzjb1tfgOf65wDizUQvQ/UVDqL/VQExNI=,tag:4W6KvNv9jp5kcyogOV6Hng==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
